<?php

namespace AppBundle\Repository;

/**
 * solicitud_notaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class solicitud_notaRepository extends \Doctrine\ORM\EntityRepository
{
}
