<?php

namespace AppBundle\Repository;

/**
 * usuario_campos_afinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuario_campos_afinesRepository extends \Doctrine\ORM\EntityRepository
{
}
